

ALL:dlt_104_port_com.o dlt_104_port_sys.o

dlt_104_port_com.o:dlt_104_port_com.c
	gcc-5 -c -Wall -g -I../inc dlt_104_port_com.c -o ../obj/dlt_104_port_com.o  
dlt_104_port_sys.o:dlt_104_port_sys.c
	gcc-5 -c -Wall -g -I../inc dlt_104_port_sys.c -o ../obj/dlt_104_port_sys.o  
clean:
	rm -vf *.o *.a 






























