

All:dlt_104.o dlt_104_init.o dlt_104_lib.o dlt_104_call.o dlt_104_time.o dlt_104_soe.o dlt_104_param.o dlt_104_elect.o dlt_104_misc.o


dlt_104.o:dlt_104.c
	gcc-5 -c -Wall -g -I../inc dlt_104.c -o ../obj/dlt_104.o 

dlt_104_init.o:dlt_104_init.c
	gcc-5 -c -Wall -g -I../inc dlt_104_init.c -o ../obj/dlt_104_init.o 

dlt_104_lib.o:dlt_104_lib.c
	gcc-5 -c -Wall -g -I../inc dlt_104_lib.c -o ../obj/dlt_104_lib.o 

dlt_104_call.o:dlt_104_call.c
	gcc-5 -c -Wall -g -I../inc dlt_104_call.c -o ../obj/dlt_104_call.o 

dlt_104_time.o:dlt_104_time.c
	gcc-5 -c -Wall -g -I../inc dlt_104_time.c -o ../obj/dlt_104_time.o 

dlt_104_soe.o:dlt_104_soe.c
	gcc-5 -c -Wall -g -I../inc dlt_104_soe.c -o ../obj/dlt_104_soe.o 

dlt_104_param.o:dlt_104_param.c
	gcc-5 -c -Wall -g -I../inc dlt_104_param.c -o ../obj/dlt_104_param.o
 
dlt_104_elect.o:dlt_104_elect.c
	gcc-5 -c -Wall -g -I../inc dlt_104_elect.c -o ../obj/dlt_104_elect.o

dlt_104_misc.o:dlt_104_misc.c
	gcc-5 -c -Wall -g -I../inc dlt_104_misc.c -o ../obj/dlt_104_misc.o

clean:
	rm -vf *.o *.a 






























